# Generated by Django 5.0.1 on 2026-01-28 06:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('work_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('WORK_FROM_HOME', 'Work From Home'), ('ON_LEAVE', 'On Leave'), ('HOLIDAY', 'Holiday'), ('WEEKEND', 'Weekend')], default='ABSENT', max_length=20)),
                ('check_in_location', models.JSONField(blank=True, null=True)),
                ('check_out_location', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_manual_entry', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('work_hours_per_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('work_days_per_week', models.IntegerField(default=5)),
                ('standard_check_in_time', models.TimeField(help_text='e.g., 09:00')),
                ('standard_check_out_time', models.TimeField(help_text='e.g., 18:00')),
                ('grace_period_minutes', models.IntegerField(default=15, help_text='Grace period for late arrival')),
                ('half_day_hours', models.DecimalField(decimal_places=2, default=4.0, max_digits=4)),
                ('weekend_days', models.JSONField(default=list, help_text='List of weekend day numbers (0=Monday, 6=Sunday)')),
                ('allow_overtime', models.BooleanField(default=False)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=3)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'attendance_policies',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True, help_text='If False, employees can choose to work')),
            ],
            options={
                'db_table': 'holidays',
                'ordering': ['date'],
            },
        ),
    ]
