# Generated by Django 5.0.1 on 2026-01-28 06:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_salary', models.DecimalField(decimal_places=2, help_text='Gross monthly salary', max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, help_text='Net monthly salary after deductions', max_digits=12)),
                ('custom_components', models.JSONField(blank=True, default=dict, help_text='Employee-specific component overrides')),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'employee_salaries',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('components_breakdown', models.JSONField(default=dict)),
                ('deductions_breakdown', models.JSONField(default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payroll_records',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('components', models.JSONField(default=dict, help_text='Salary components and amounts')),
                ('deductions', models.JSONField(default=dict, help_text='Deduction types and percentages/amounts')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'salary_structures',
                'ordering': ['name'],
            },
        ),
    ]
