# Generated by Django 5.0.1 on 2026-01-28 06:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('RESUME', 'Resume'), ('OFFER_LETTER', 'Offer Letter'), ('APPOINTMENT_LETTER', 'Appointment Letter'), ('ID_PROOF', 'ID Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('EDUCATION_CERTIFICATE', 'Education Certificate'), ('EXPERIENCE_LETTER', 'Experience Letter'), ('PAYSLIP', 'Payslip'), ('TAX_DOCUMENT', 'Tax Document'), ('OTHER', 'Other')], max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(help_text='Path to stored file', max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='MIME type', max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Required for all employees')),
            ],
            options={
                'verbose_name_plural': 'Document Categories',
                'db_table': 'document_categories',
                'ordering': ['name'],
            },
        ),
    ]
