# Generated by Django 5.0.1 on 2026-01-28 06:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Company name', max_length=255)),
                ('code', models.CharField(help_text='Unique company code (used for employee IDs)', max_length=50, unique=True)),
                ('subdomain', models.CharField(blank=True, help_text='Subdomain for tenant (e.g., acme.hrms.com)', max_length=100, null=True, unique=True)),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('subscription_plan', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=50)),
                ('max_employees', models.IntegerField(default=10)),
                ('max_storage_mb', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_trial', models.BooleanField(default=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Tenant-specific settings')),
                ('logo', models.CharField(blank=True, max_length=500)),
                ('primary_color', models.CharField(default='#1976d2', max_length=7)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
    ]
