# Generated by Django 5.0.1 on 2026-01-28 06:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(help_text='Financial year')),
                ('total_days', models.DecimalField(decimal_places=2, help_text='Total allocated days', max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=2, default=0.0, help_text='Days used', max_digits=5)),
                ('pending_days', models.DecimalField(decimal_places=2, default=0.0, help_text='Days in pending requests', max_digits=5)),
            ],
            options={
                'db_table': 'leave_balances',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('days', models.DecimalField(decimal_places=2, help_text='Number of leave days', max_digits=5)),
                ('reason', models.TextField()),
                ('contact_during_leave', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'leave_requests',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('EARNED', 'Earned Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('UNPAID', 'Unpaid Leave'), ('COMPENSATORY', 'Compensatory Off')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('days_per_year', models.IntegerField(help_text='Annual leave allocation')),
                ('max_carry_forward', models.IntegerField(default=0, help_text='Max days that can be carried to next year')),
                ('requires_approval', models.BooleanField(default=True)),
                ('min_days_notice', models.IntegerField(default=1, help_text='Minimum days notice required')),
                ('max_consecutive_days', models.IntegerField(default=30, help_text='Maximum consecutive days allowed')),
                ('is_paid', models.BooleanField(default=True)),
                ('applicable_after_months', models.IntegerField(default=0, help_text='Applicable after X months of employment')),
                ('gender_specific', models.CharField(blank=True, choices=[('', 'All'), ('MALE', 'Male Only'), ('FEMALE', 'Female Only')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'leave_types',
                'ordering': ['name'],
            },
        ),
    ]
